#!/bin/bash

DATE=$(date +"%T")
URLFILE="top_10000.txt"
INCREMENT=100
ITERATIONS=1
START=0


RESULTS="Logs/results-$DATE.txt"
let END=$INCREMENT*$ITERATIONS+$START
let ADJUSTEDITER=$ITERATIONS-1
echo "Running Campaign in increments of $INCREMENT" | tee -a $RESULTS
echo "" | tee -a $RESULTS

for BATCH in `seq 0 $ADJUSTEDITER`; do
    let LOCALSTART=$INCREMENT*$BATCH+$START
    echo "Currently running batch starting at $LOCALSTART" | tee -a $RESULTS
    ./batch.py -batch $URLFILE $LOCALSTART $INCREMENT 2>&- | tee -a $RESULTS
    echo "" | tee -a $RESULTS
done

echo "Ran from $START to $END on $URLFILE" | tee -a $RESULTS
