#!/bin/bash

DATE=$(date +"%T")
URLFILE="datasets/URLs.txt"
INCREMENT=5
ITERATIONS=1
START=0


RESULTS="Logs/results-Chains-$DATE.txt"
ERROR="Logs/error-results-Chains-$DATE.txt"
let END=$INCREMENT*$ITERATIONS+$START
let ADJUSTEDITER=$ITERATIONS-1
echo "Running Campaign in increments of $INCREMENT" | tee -a $RESULTS
echo "" | tee -a $RESULTS

for BATCH in `seq 0 $ADJUSTEDITER`; do
    let LOCALSTART=$INCREMENT*$BATCH+$START
    echo "Currently running batch starting at $LOCALSTART" | tee -a $RESULTS
    ./chains.py -batch $URLFILE $LOCALSTART $INCREMENT 2>$ERROR | tee -a $RESULTS
    echo "" | tee -a $RESULTS
done

echo "Ran from $START to $END on $URLFILE" | tee -a $RESULTS
